export const electronicCategories= [
  {
    category: "TVs and Screens",
    brands: [
      { value: "samsung", label: "Samsung" },
      { value: "lg", label: "LG" },
      { value: "sony", label: "Sony" },
      { value: "panasonic", label: "Panasonic" },
      { value: "onida", label: "Onida" },
      { value: "mi", label: "Mi" },
      { value: "vu", label: "Vu" },
      { value: "tcl", label: "TCL" },
      { value: "philips", label: "Philips" },
      { value: "realme", label: "Realme" },
      { value: "thomson", label: "Thomson" },
      { value: "kodak", label: "Kodak" },
      { value: "bpl", label: "BPL" },
      { value: "hisense", label: "Hisense" },
      { value: "others", label: "Others" },
    ],
  },
  {
    category: "Computer & Laptops",
    brands: [
      { value: "hp", label: "HP" },
      { value: "dell", label: "Dell" },
      { value: "lenovo", label: "Lenovo" },
      { value: "acer", label: "Acer" },
      { value: "asus", label: "Asus" },
      { value: "apple", label: "Apple" },
      { value: "msi", label: "MSI" },
      { value: "samsung", label: "Samsung" },
      { value: "microsoft", label: "Microsoft" },
      { value: "avita", label: "Avita" },
      { value: "lg", label: "LG" },
      { value: "hcl", label: "HCL" },
      { value: "fujitsu", label: "Fujitsu" },
      { value: "iball", label: "iBall" },
      { value: "others", label: "Others" },
    ],
  },
  {
    category: "Fridges",
    brands: [
      { value: "lg", label: "LG" },
      { value: "samsung", label: "Samsung" },
      { value: "whirlpool", label: "Whirlpool" },
      { value: "haier", label: "Haier" },
      { value: "godrej", label: "Godrej" },
      { value: "bosch", label: "Bosch" },
      { value: "hitachi", label: "Hitachi" },
      { value: "panasonic", label: "Panasonic" },
      { value: "voltas-beko", label: "Voltas Beko" },
      { value: "kelvinator", label: "Kelvinator" },
      { value: "siemens", label: "Siemens" },
      { value: "electrolux", label: "Electrolux" },
      { value: "croma", label: "Croma" },
      { value: "ifb", label: "IFB" },
      { value: "others", label: "Others" },
    ],
  },
  {
    category: "Mobile/Tablets",
    brands: [
      { value: "samsung", label: "Samsung" },
      { value: "apple", label: "Apple" },
      { value: "realme", label: "Realme" },
      { value: "xiaomi", label: "Xiaomi" },
      { value: "vivo", label: "Vivo" },
      { value: "oppo", label: "Oppo" },
      { value: "oneplus", label: "OnePlus" },
      { value: "motorola", label: "Motorola" },
      { value: "iqoo", label: "iQOO" },
      { value: "nokia", label: "Nokia" },
      { value: "asus", label: "Asus" },
      { value: "infinix", label: "Infinix" },
      { value: "tecno", label: "Tecno" },
      { value: "micromax", label: "Micromax" },
      { value: "others", label: "Others" },
    ],
  },
  {
    category: "Mobile Accessories",
    brands: [
      { value: "boat", label: "Boat" },
      { value: "noise", label: "Noise" },
      { value: "zebronics", label: "Zebronics" },
      { value: "ambrane", label: "Ambrane" },
      { value: "portronics", label: "Portronics" },
      { value: "ptron", label: "pTron" },
      { value: "mi", label: "Mi" },
      { value: "realme", label: "Realme" },
      { value: "jbl", label: "JBL" },
      { value: "boult", label: "Boult" },
      { value: "anker", label: "Anker" },
      { value: "stuffcool", label: "Stuffcool" },
      { value: "artis", label: "Artis" },
      { value: "syska", label: "Syska" },
      { value: "others", label: "Others" },
    ],
  },
  {
    category: "Computer Accessories",
    brands: [
      { value: "logitech", label: "Logitech" },
      { value: "zebronics", label: "Zebronics" },
      { value: "amkette", label: "Amkette" },
      { value: "redgear", label: "Redgear" },
      { value: "circle", label: "Circle" },
      { value: "dell", label: "Dell" },
      { value: "hp", label: "HP" },
      { value: "razer", label: "Razer" },
      { value: "corsair", label: "Corsair" },
      { value: "cooler-master", label: "Cooler Master" },
      { value: "cosmic-byte", label: "Cosmic Byte" },
      { value: "hyperx", label: "HyperX" },
      { value: "frontech", label: "Frontech" },
      { value: "enter", label: "Enter" },
      { value: "others", label: "Others" },
    ],
  },
  {
    category: "Gaming Accessories",
    brands: [
      { value: "sony", label: "Sony" },
      { value: "microsoft", label: "Microsoft" },
      { value: "nintendo", label: "Nintendo" },
      { value: "redgear", label: "Redgear" },
      { value: "cosmic-byte", label: "Cosmic Byte" },
      { value: "hyperx", label: "HyperX" },
      { value: "razer", label: "Razer" },
      { value: "gamesir", label: "GameSir" },
      { value: "powera", label: "PowerA" },
      { value: "steelseries", label: "SteelSeries" },
      { value: "logitech-g", label: "Logitech G" },
      { value: "astro", label: "Astro" },
      { value: "hori", label: "Hori" },
      { value: "8bitdo", label: "8BitDo" },
      { value: "others", label: "Others" },
    ],
  },
  {
    category: "Washing Machine",
    brands: [
      { value: "lg", label: "LG" },
      { value: "samsung", label: "Samsung" },
      { value: "whirlpool", label: "Whirlpool" },
      { value: "ifb", label: "IFB" },
      { value: "bosch", label: "Bosch" },
      { value: "haier", label: "Haier" },
      { value: "godrej", label: "Godrej" },
      { value: "panasonic", label: "Panasonic" },
      { value: "daikin", label: "Daikin" },
      { value: "voltas-beko", label: "Voltas Beko" },
      { value: "siemens", label: "Siemens" },
      { value: "electrolux", label: "Electrolux" },
      { value: "lloyd", label: "Lloyd" },
      { value: "videocon", label: "Videocon" },
      { value: "others", label: "Others" },
    ],
  },
  {
    category: "AC",
    brands: [
      { value: "lg", label: "LG" },
      { value: "samsung", label: "Samsung" },
      { value: "voltas", label: "Voltas" },
      { value: "blue-star", label: "Blue Star" },
      { value: "godrej", label: "Godrej" },
      { value: "whirlpool", label: "Whirlpool" },
      { value: "daikin", label: "Daikin" },
      { value: "panasonic", label: "Panasonic" },
      { value: "hitachi", label: "Hitachi" },
      { value: "carrier", label: "Carrier" },
      { value: "siemens", label: "Siemens" },
      { value: "haier", label: "Haier" },
      { value: "lloyd", label: "Lloyd" },
      { value: "midea", label: "Midea" },
      { value: "others", label: "Others" },
    ],
  },
  {
    category: "Camera/Lenses",
    brands: [
      { value: "canon", label: "Canon" },
      { value: "nikon", label: "Nikon" },
      { value: "sony", label: "Sony" },
      { value: "fujifilm", label: "Fujifilm" },
      { value: "panasonic", label: "Panasonic" },
      { value: "olympus", label: "Olympus" },
      { value: "leica", label: "Leica" },
      { value: "pentax", label: "Pentax" },
      { value: "gopro", label: "GoPro" },
      { value: "sigma", label: "Sigma" },
      { value: "tamron", label: "Tamron" },
      { value: "zeiss", label: "Zeiss" },
      { value: "polaroid", label: "Polaroid" },
      { value: "dji", label: "DJI" },
      { value: "others", label: "Others" },
    ],
  },
  {
    category: "Other",
    brands: [{ value: "others", label: "Others" }],
  },
]  as const
